### ISSUE TITLE
Multiple errors when using the programming Interface

### ISSUE THREAD

**Issue by unixfox** [tewarid/node-tcp-proxy#12]
NodeJS version: v13.8.0

I'm trying to use the [example](https://github.com/tewarid/node-tcp-proxy#programming-interface) from the README but it doesn't work.
My first error is:
```
/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:21
        throw new Error("cannot parse object: " + o);
        ^

Error: cannot parse object: 10080
    at parse (/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:21:15)
    at new TcpProxy (/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:28:25)
    at Object.module.exports.createProxy (/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:7:12)
    at Object.<anonymous> (/tmp/test.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
````
Then I change the port `10080` to a string:
````js
var proxy = require("node-tcp-proxy");
var newProxy = proxy.createProxy(8080, "host", "10080");
````

After that I get a second error:
````
internal/fs/utils.js:534
    throw new ERR_INVALID_ARG_TYPE(propName, ['string', 'Buffer', 'URL'], path);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.openSync (fs.js:449:10)
    at Object.readFileSync (fs.js:359:35)
    at new TcpProxy (/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:40:39)
    at Object.module.exports.createProxy (/tmp/node_modules/node-tcp-proxy/tcp-proxy.js:7:12)
    at Object.<anonymous> (/tmp/test.js:2:22)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'ERR_INVALID_ARG_TYPE'
}
````

**Comment by tewarid** [comment]
Just realized that these issues have been fixed a while. I've pushed out a new package version to npm. Please update and try. Thank you.
