### ISSUE TITLE
Error in  context.serviceSocket.destroy();

### ISSUE THREAD

**Issue by vasusharma7** [tewarid/node-tcp-proxy#16]
![Screenshot from 2020-11-06 14-30-56](https://user-images.githubusercontent.com/40715071/98346986-ccbd0b80-203c-11eb-807d-97d2901592ea.png)

The connection breaks on serving one client and it returns the following error.

```
Allow all users
/home/ubuntu/torrent/node_modules/node-tcp-proxy/tcp-proxy.js:137
        context.serviceSocket.destroy();
                              ^

TypeError: Cannot read property 'destroy' of undefined
    at Socket.<anonymous> (/home/ubuntu/torrent/node_modules/node-tcp-proxy/tcp-proxy.js:137:31)
    at Socket.emit (events.js:315:20)
    at TCP.<anonymous> (net.js:674:12)

```

**Comment by tewarid** [comment]
@vasusharma7 I've added a check for undefined. Thanks!
